### ISSUE TITLE
Lab asks user to make file that already exists

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/playlister-on-activerecord#13]
User: Artem Eremin

Batch: 000

Current Lesson: Playlister on ActiveRecord

Location: https://learn.co/tracks/web-development-with-ruby-on-rails/object-relational-mappers-orms/activerecord-associations/playlister-on-activerecord?track_id=5309&batch_id=76

Bug Description: Please look at 1) MODELS. It's written "you'll need to make one for your `Song` model", but in fact this file is already there with a model class inside.

**Comment by AnnJohn** [comment]
Iceboxing for now
