### ISSUE TITLE
students having issue running any lines in terminal with this lab

### ISSUE THREAD

**Issue by laurkim** [learn-co-curriculum/playlister-on-activerecord#28]
some students receive the error: 

../playlister-on-activerecord-web-091817/lib/support/db_registry.rb:3:in `<top (required)>': uninitialized constant ConnectionAdapter (NameError)

Issue is fixed if the "require_all" gem is added to the Gemfile and you add the below to the environment.rb file:
`require_all 'app'
require_all 'lib'`

**Comment by aviflombaum** [comment]
Fixed
